# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/common_attributes_reporters_inner.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@kessel/inventory/v1beta1/common_attributes_reporters_inner.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\"\x82\x01\n\x1e\x43ommonAttributesReportersInner\x12\x0f\n\x04Type\x18\xda\x86\xa0\x01 \x01(\t\x12 \n\x14reporter_instance_id\x18\xa7\xa5\x84\xf5\x01 \x01(\t\x12\x13\n\x07\x63reated\x18\xe9\xfd\xb9\xea\x01 \x01(\t\x12\x18\n\x0clast_updated\x18\x92\xc8\xc0\xa1\x01 \x01(\tBF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.common_attributes_reporters_inner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_COMMONATTRIBUTESREPORTERSINNER']._serialized_start=99
  _globals['_COMMONATTRIBUTESREPORTERSINNER']._serialized_end=229
# @@protoc_insertion_point(module_scope)
