# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/error.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$kessel/inventory/v1beta1/error.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\"f\n\x05\x45rror\x12\x0f\n\x04type\x18\xba\x9e\xda\x01 \x01(\t\x12\x10\n\x05title\x18\xd8\xc4\xd0\x34 \x01(\t\x12\x12\n\x06status\x18\x8f\xe0\xc8\xa9\x01 \x01(\x05\x12\x11\n\x06\x64\x65tail\x18\xb1\xcf\xd7| \x01(\t\x12\x13\n\x08instance\x18\x96\xa9\xda\x08 \x01(\tBF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_ERROR']._serialized_start=70
  _globals['_ERROR']._serialized_end=172
# @@protoc_insertion_point(module_scope)
