# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/k8s_cluster_detail_nodes_inner.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kessel.inventory.v1beta1 import resource_tag_pb2 as kessel_dot_inventory_dot_v1beta1_dot_resource__tag__pb2

from kessel.inventory.v1beta1.resource_tag_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=kessel/inventory/v1beta1/k8s_cluster_detail_nodes_inner.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\x1a+kessel/inventory/v1beta1/resource_tag.proto\"\x8d\x01\n\x1aK8sClusterDetailNodesInner\x12\x0f\n\x04name\x18\x8b\xf5\xcd\x01 \x01(\t\x12\r\n\x03\x63pu\x18\xa8\x83\x06 \x01(\t\x12\x11\n\x06memory\x18\x81\x86\xf5\x01 \x01(\t\x12<\n\x06labels\x18\x83\xc0\xbe\x11 \x03(\x0b\x32).api.kessel.inventory.v1beta1.ResourceTagBF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.k8s_cluster_detail_nodes_inner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_K8SCLUSTERDETAILNODESINNER']._serialized_start=141
  _globals['_K8SCLUSTERDETAILNODESINNER']._serialized_end=282
# @@protoc_insertion_point(module_scope)
