# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kessel.inventory.v1beta1 import k8s_clusters_service_pb2 as kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kessel/inventory/v1beta1/k8s_clusters_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class K8sClustersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateK8sCluster = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.K8sClustersService/CreateK8sCluster',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterResponse.FromString,
                _registered_method=True)
        self.UpdateK8sCluster = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.K8sClustersService/UpdateK8sCluster',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterResponse.FromString,
                _registered_method=True)
        self.DeleteK8sCluster = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.K8sClustersService/DeleteK8sCluster',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterResponse.FromString,
                _registered_method=True)


class K8sClustersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateK8sCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateK8sCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteK8sCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_K8sClustersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateK8sCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateK8sCluster,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterResponse.SerializeToString,
            ),
            'UpdateK8sCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateK8sCluster,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterResponse.SerializeToString,
            ),
            'DeleteK8sCluster': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteK8sCluster,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.kessel.inventory.v1beta1.K8sClustersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.kessel.inventory.v1beta1.K8sClustersService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class K8sClustersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateK8sCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.K8sClustersService/CreateK8sCluster',
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.CreateK8sClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateK8sCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.K8sClustersService/UpdateK8sCluster',
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.UpdateK8sClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteK8sCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.K8sClustersService/DeleteK8sCluster',
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_k8s__clusters__service__pb2.DeleteK8sClusterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
