# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kessel.inventory.v1beta1 import notifications_integrations_service_pb2 as kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kessel/inventory/v1beta1/notifications_integrations_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class NotificationsIntegrationsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotificationsIntegration = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/CreateNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.FromString,
                _registered_method=True)
        self.UpdateNotificationsIntegration = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/UpdateNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.FromString,
                _registered_method=True)
        self.DeleteNotificationsIntegration = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/DeleteNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.FromString,
                _registered_method=True)


class NotificationsIntegrationsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationsIntegrationsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.SerializeToString,
            ),
            'UpdateNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.SerializeToString,
            ),
            'DeleteNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.kessel.inventory.v1beta1.NotificationsIntegrationsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.kessel.inventory.v1beta1.NotificationsIntegrationsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationsIntegrationsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/CreateNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/UpdateNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.NotificationsIntegrationsService/DeleteNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
