# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/policies_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from kessel.inventory.v1beta1 import policy_pb2 as kessel_dot_inventory_dot_v1beta1_dot_policy__pb2
try:
  kessel_dot_inventory_dot_v1beta1_dot_metadata__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel_dot_inventory_dot_v1beta1_dot_metadata__pb2
except AttributeError:
  kessel_dot_inventory_dot_v1beta1_dot_metadata__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel.inventory.v1beta1.metadata_pb2
try:
  kessel_dot_inventory_dot_v1beta1_dot_resource__tag__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel_dot_inventory_dot_v1beta1_dot_resource__tag__pb2
except AttributeError:
  kessel_dot_inventory_dot_v1beta1_dot_resource__tag__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel.inventory.v1beta1.resource_tag_pb2
try:
  kessel_dot_inventory_dot_v1beta1_dot_policy__detail__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel_dot_inventory_dot_v1beta1_dot_policy__detail__pb2
except AttributeError:
  kessel_dot_inventory_dot_v1beta1_dot_policy__detail__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel.inventory.v1beta1.policy_detail_pb2
try:
  kessel_dot_inventory_dot_v1beta1_dot_reporter__data__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel_dot_inventory_dot_v1beta1_dot_reporter__data__pb2
except AttributeError:
  kessel_dot_inventory_dot_v1beta1_dot_reporter__data__pb2 = kessel_dot_inventory_dot_v1beta1_dot_policy__pb2.kessel.inventory.v1beta1.reporter_data_pb2

from kessel.inventory.v1beta1.policy_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/kessel/inventory/v1beta1/policies_service.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\x1a\x1cgoogle/api/annotations.proto\x1a%kessel/inventory/v1beta1/policy.proto\"K\n\x13\x43reatePolicyRequest\x12\x34\n\x06policy\x18\x01 \x01(\x0b\x32$.api.kessel.inventory.v1beta1.Policy\"L\n\x14\x43reatePolicyResponse\x12\x34\n\x06policy\x18\x01 \x01(\x0b\x32$.api.kessel.inventory.v1beta1.Policy\"]\n\x13UpdatePolicyRequest\x12\x10\n\x08resource\x18\x01 \x01(\t\x12\x34\n\x06policy\x18\x02 \x01(\x0b\x32$.api.kessel.inventory.v1beta1.Policy\"\x16\n\x14UpdatePolicyResponse\"\'\n\x13\x44\x65letePolicyRequest\x12\x10\n\x08resource\x18\x01 \x01(\t\"\x16\n\x14\x44\x65letePolicyResponse2\x9a\x04\n\x0fPoliciesService\x12\xa6\x01\n\x0c\x43reatePolicy\x12\x31.api.kessel.inventory.v1beta1.CreatePolicyRequest\x1a\x32.api.kessel.inventory.v1beta1.CreatePolicyResponse\"/\x82\xd3\xe4\x93\x02)\"\x1f/api/inventory/v1beta1/policies:\x06policy\x12\xb1\x01\n\x0cUpdatePolicy\x12\x31.api.kessel.inventory.v1beta1.UpdatePolicyRequest\x1a\x32.api.kessel.inventory.v1beta1.UpdatePolicyResponse\":\x82\xd3\xe4\x93\x02\x34\x1a*/api/inventory/v1beta1/policies/{resource}:\x06policy\x12\xa9\x01\n\x0c\x44\x65letePolicy\x12\x31.api.kessel.inventory.v1beta1.DeletePolicyRequest\x1a\x32.api.kessel.inventory.v1beta1.DeletePolicyResponse\"2\x82\xd3\xe4\x93\x02,**/api/inventory/v1beta1/policies/{resource}BF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.policies_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_POLICIESSERVICE'].methods_by_name['CreatePolicy']._loaded_options = None
  _globals['_POLICIESSERVICE'].methods_by_name['CreatePolicy']._serialized_options = b'\202\323\344\223\002)\"\037/api/inventory/v1beta1/policies:\006policy'
  _globals['_POLICIESSERVICE'].methods_by_name['UpdatePolicy']._loaded_options = None
  _globals['_POLICIESSERVICE'].methods_by_name['UpdatePolicy']._serialized_options = b'\202\323\344\223\0024\032*/api/inventory/v1beta1/policies/{resource}:\006policy'
  _globals['_POLICIESSERVICE'].methods_by_name['DeletePolicy']._loaded_options = None
  _globals['_POLICIESSERVICE'].methods_by_name['DeletePolicy']._serialized_options = b'\202\323\344\223\002,**/api/inventory/v1beta1/policies/{resource}'
  _globals['_CREATEPOLICYREQUEST']._serialized_start=150
  _globals['_CREATEPOLICYREQUEST']._serialized_end=225
  _globals['_CREATEPOLICYRESPONSE']._serialized_start=227
  _globals['_CREATEPOLICYRESPONSE']._serialized_end=303
  _globals['_UPDATEPOLICYREQUEST']._serialized_start=305
  _globals['_UPDATEPOLICYREQUEST']._serialized_end=398
  _globals['_UPDATEPOLICYRESPONSE']._serialized_start=400
  _globals['_UPDATEPOLICYRESPONSE']._serialized_end=422
  _globals['_DELETEPOLICYREQUEST']._serialized_start=424
  _globals['_DELETEPOLICYREQUEST']._serialized_end=463
  _globals['_DELETEPOLICYRESPONSE']._serialized_start=465
  _globals['_DELETEPOLICYRESPONSE']._serialized_end=487
  _globals['_POLICIESSERVICE']._serialized_start=490
  _globals['_POLICIESSERVICE']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
