# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kessel.inventory.v1beta1 import policies_service_pb2 as kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kessel/inventory/v1beta1/policies_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PoliciesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePolicy = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.PoliciesService/CreatePolicy',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.PoliciesService/UpdatePolicy',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyResponse.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.PoliciesService/DeletePolicy',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyResponse.FromString,
                _registered_method=True)


class PoliciesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PoliciesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyResponse.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.kessel.inventory.v1beta1.PoliciesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.kessel.inventory.v1beta1.PoliciesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PoliciesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.PoliciesService/CreatePolicy',
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.CreatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.PoliciesService/UpdatePolicy',
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.UpdatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.PoliciesService/DeletePolicy',
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_policies__service__pb2.DeletePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
