# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from kessel.inventory.v1beta1 import relationships_service_pb2 as kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2

GRPC_GENERATED_VERSION = '1.65.2'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kessel/inventory/v1beta1/relationships_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class RelationshipsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePolicyRelationship = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.RelationshipsService/CreatePolicyRelationship',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipResponse.FromString,
                _registered_method=True)
        self.UpdateResourceRelationshipByURNHs = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.RelationshipsService/UpdateResourceRelationshipByURNHs',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNHsRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNResponse.FromString,
                _registered_method=True)
        self.DeleteResourceRelationshipByURN = channel.unary_unary(
                '/api.kessel.inventory.v1beta1.RelationshipsService/DeleteResourceRelationshipByURN',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNResponse.FromString,
                _registered_method=True)


class RelationshipsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePolicyRelationship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateResourceRelationshipByURNHs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteResourceRelationshipByURN(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RelationshipsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePolicyRelationship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicyRelationship,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipResponse.SerializeToString,
            ),
            'UpdateResourceRelationshipByURNHs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateResourceRelationshipByURNHs,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNHsRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNResponse.SerializeToString,
            ),
            'DeleteResourceRelationshipByURN': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteResourceRelationshipByURN,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.kessel.inventory.v1beta1.RelationshipsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.kessel.inventory.v1beta1.RelationshipsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RelationshipsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePolicyRelationship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.RelationshipsService/CreatePolicyRelationship',
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.CreatePolicyRelationshipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateResourceRelationshipByURNHs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.RelationshipsService/UpdateResourceRelationshipByURNHs',
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNHsRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.UpdateResourceRelationshipByURNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteResourceRelationshipByURN(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/api.kessel.inventory.v1beta1.RelationshipsService/DeleteResourceRelationshipByURN',
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_relationships__service__pb2.DeleteResourceRelationshipByURNResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
