# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/resource_tags.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kessel.inventory.v1beta1 import resource_tag_pb2 as kessel_dot_inventory_dot_v1beta1_dot_resource__tag__pb2

from kessel.inventory.v1beta1.resource_tag_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,kessel/inventory/v1beta1/resource_tags.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\x1a+kessel/inventory/v1beta1/resource_tag.proto\"J\n\x0cResourceTags\x12:\n\x04tags\x18\x99\xe8\xd8\x01 \x03(\x0b\x32).api.kessel.inventory.v1beta1.ResourceTagBF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1P\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.resource_tags_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_RESOURCETAGS']._serialized_start=123
  _globals['_RESOURCETAGS']._serialized_end=197
# @@protoc_insertion_point(module_scope)
