# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kessel/inventory/v1beta1/update_resource_relationship_by_urnhs_resources_parameter.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nXkessel/inventory/v1beta1/update_resource_relationship_by_urnhs_resources_parameter.proto\x12\x1c\x61pi.kessel.inventory.v1beta1\"n\n3UpdateResourceRelationshipByURNHsResourcesParameter\x12\x1b\n\x10subject_resource\x18\xc0\x9c\xa9\t \x01(\t\x12\x1a\n\x0fobject_resource\x18\x91\x92\xaay \x01(\tBF\n\x1c\x61pi.kessel.inventory.v1beta1P\x01Z$api/kessel/inventory/v1beta1;v1beta1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kessel.inventory.v1beta1.update_resource_relationship_by_urnhs_resources_parameter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034api.kessel.inventory.v1beta1P\001Z$api/kessel/inventory/v1beta1;v1beta1'
  _globals['_UPDATERESOURCERELATIONSHIPBYURNHSRESOURCESPARAMETER']._serialized_start=122
  _globals['_UPDATERESOURCERELATIONSHIPBYURNHSRESOURCESPARAMETER']._serialized_end=232
# @@protoc_insertion_point(module_scope)
