# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from kessel.inventory.v1beta1.resources import notifications_integrations_service_pb2 as kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2


class KesselNotificationsIntegrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNotificationsIntegration = channel.unary_unary(
                '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/CreateNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.FromString,
                _registered_method=True)
        self.UpdateNotificationsIntegration = channel.unary_unary(
                '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/UpdateNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.FromString,
                _registered_method=True)
        self.DeleteNotificationsIntegration = channel.unary_unary(
                '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/DeleteNotificationsIntegration',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.FromString,
                _registered_method=True)
        self.ListNotificationsIntegrations = channel.unary_stream(
                '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/ListNotificationsIntegrations',
                request_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsRequest.SerializeToString,
                response_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsResponse.FromString,
                _registered_method=True)


class KesselNotificationsIntegrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNotificationsIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNotificationsIntegrations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KesselNotificationsIntegrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.SerializeToString,
            ),
            'UpdateNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.SerializeToString,
            ),
            'DeleteNotificationsIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNotificationsIntegration,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.SerializeToString,
            ),
            'ListNotificationsIntegrations': grpc.unary_stream_rpc_method_handler(
                    servicer.ListNotificationsIntegrations,
                    request_deserializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsRequest.FromString,
                    response_serializer=kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KesselNotificationsIntegrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/CreateNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.CreateNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/UpdateNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.UpdateNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNotificationsIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/DeleteNotificationsIntegration',
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.DeleteNotificationsIntegrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNotificationsIntegrations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kessel.inventory.v1beta1.resources.KesselNotificationsIntegrationService/ListNotificationsIntegrations',
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsRequest.SerializeToString,
            kessel_dot_inventory_dot_v1beta1_dot_resources_dot_notifications__integrations__service__pb2.ListNotificationsIntegrationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
